### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by ValseLee** [ValseLee/TCA_Workshop#1]
### TCA_Workshop_Text
* [x] 이상한 줄바꿈 정리
* [x] 1차 워크숍 내용 검토
* [x] Readme에 있는 거 나중에 Wiki로 옮기기

### TCA_Workshop_Code
* [x] .run { } 에서 리턴받고 바로 State에 할당하는 건 안된다! 는 예시 코드 작성
* [x] 테스트 코드 준비
  * [x] MVVM이랑 TCA 둘 다 준비
  * [x] Testable Async
* [x] 네비게이션 코드 준비

**Comment by ValseLee** [comment]
비동기 테스트 코드는 `mock`을 쓰지 않으면 의미가 없는데 `mock` 을 어떻게 쓰는지 모르는 사람이 나에요

**Comment by ValseLee** [comment]
#4 에서 client를 구현했으니 fetch 할 때는 서버 의존성 없이 테스트를 할 수 있다.
이제 테스트 코드 써야함

**Comment by ValseLee** [comment]
<img width="887" alt="Screenshot 2023-08-23 at 16 13 40" src="https://github.com/ValseLee/TCA_Workshop/assets/82270058/88bb8a08-eb9f-4434-98ef-2ef9f13e6697">
pod을 쓰지 않는데도 이러면 너무 슬퍼..

1. NetworkClient 서버 의존성 없이 mock으로 Test 코드 작성 및 진행 완료!
2. 각주 설명 처리 완료

**Comment by ValseLee** [comment]
위키로 옮기는중!

**Comment by ValseLee** [comment]
Readme Update를 마치고 나서 옮겨야 wiki 섹션을 나눌 수 있을듯
천천히 준비

**Comment by ValseLee** [comment]
Readme 예시코드들 각주 전부 스타일 다른거 진짜 열밧네 수정필

**Comment by ValseLee** [comment]
Wiki 이사 끗!!!
근데 각주 스타일 수정해야함

**Comment by ValseLee** [comment]
1. 각주 스타일 수정해야 하고
2. Firebase 의존성 치워야해
3. 그리고 책도 집필 해야지..

**Comment by ValseLee** [comment]
Firebase 의존성은 치웠는데
mock 서버가 수정은 안되는 관계로... 내가 서버를 만들던가 해야 함

**Comment by ValseLee** [comment]
눈떠보니 Realm - Atlas 를 만지고 있는 나
